### ISSUE TITLE
A humble request

### ISSUE THREAD

**Issue by paradoxmr24** [Anmol270900/AnmolPortfolio#10]
Hello Anmol, I have created a pull request on your repository around 15 days ago, and now I am facing a little problem that you can easily solve, just by adding hacktoberfest topic to your repository or you can label my PR as hacktoberfest-accepted Its a humble request from you to please help me I will be very thankful to you

**Comment by Anmol270900** [comment]
Hey @paradoxmr24 , Sorry for the inconvenience, I have added both the hacktoberfest topic to this repo as well as hacktoberfest-accepted label to you PR.
Actually I removed the topic just a couple of days ago. Should have waited for the month end.
Anyways, Happy Hacktoberfest!
